# Generated by Django 3.1.5 on 2021-11-16 22:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('area', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326, verbose_name='Área')),
                ('ubicacion', models.CharField(max_length=200, null=True, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.CharField(default='1', max_length=20000, primary_key=True, serialize=False, verbose_name='id')),
                ('dormitorio', models.IntegerField(default=1, verbose_name='dormitorio')),
                ('bano', models.IntegerField(default=1, verbose_name='baños')),
                ('estacionamiento', models.IntegerField(default=1, verbose_name='Estacionamiento')),
                ('comuna', models.IntegerField(default=1, verbose_name='Comuna')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Area total')),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Area construida')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('condicion', models.IntegerField(default=1, verbose_name='Condicion')),
                ('resultado', models.CharField(default='3000', max_length=3000, verbose_name='Precio tasado')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
