# Generated by Django 3.1.5 on 2021-11-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=-33.03954315, max_digits=8),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-71.5554657, max_digits=9),
        ),
    ]
