# Generated by Django 3.1.5 on 2021-11-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211112_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=-33.03954315, max_digits=15),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-71.5554657, max_digits=15),
        ),
    ]
