# Generated by Django 3.1.5 on 2021-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211112_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Longitude'),
        ),
    ]
