# Generated by Django 3.1.5 on 2021-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211112_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='estacionamiento',
            field=models.IntegerField(default=1, verbose_name='Estacionamiento'),
        ),
    ]
